remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Cayman theme
description: Hybrid demo tests the integration of websites which use btt.js tag into Native apps that are using the native Android or iOS SDKs. In that case the session that is used by the native apps should also be passed on to the website so that on the dashboard we can see both in the same session.
show_downloads: false
